version: '3.6'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD", "curl","-s","-f","http://localhost:9200/_cat/health"]
    networks: 
      - stack
  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.1
    container_name: kibana
    hostname: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    healthcheck:
        test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/"]
        retries: 6
    networks: 
      - stack
    depends_on: ['elasticsearch' ]
    restart: on-failure
  filebeat:
    user: root
    image: docker.elastic.co/beats/filebeat:6.7.1
    hostname: filebeat
    container_name: filebeat
    volumes:
        - ${PWD}/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
# needed to persist filebeat tracking data :
        - "filebeat_data:/usr/share/filebeat/data:rw"
# needed to access all docker logs (read only) :
        - "/var/lib/docker/containers:/usr/share/dockerlogs/data:ro"
# needed to access additional informations about containers
        - "/var/run/docker.sock:/var/run/docker.sock"
        - ${PWD}/filebeat_inputs/apache2/:/var/log/filebeat_inputs/apache2/
    environment:
      KIBANA_HOSTS: kibana:5601
      ELASTICSEARCH_HOSTS: elasticsearch:9200
    networks:
      - stack 
    command: bash -c "filebeat setup --dashboards && filebeat -e -strict.perms=false"
    restart: on-failure
    depends_on: ['elasticsearch','kibana']
volumes:
  esdata:
  filebeat_data:
networks:
  stack:
